title: lyx聊一下
email: yixiliu@whu.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  GUI=good-looking+useful+interesting
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://yixi.cool" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: null
github_username:  LexieKeepsCool

# Build settings
theme: minima
plugins:
  - jekyll-feed
